site_name: WikiForum - 维方

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - navigation.top
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

nav:
  - 首页: index.md
  - 常识: '常识/!*.md'
  - 其他页面: '!*.md'